{{- range .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  labels:
    app: autoclose
    service: {{ .name }}
spec:
  type: ClusterIP
  selector:
    app: autoclose
    service: {{ .name }}
  ports:
    - port: {{ .port }}
      targetPort: {{ .port }}
      protocol: TCP
      name: http
---
{{- end }}
